### PR TITLE
reordered groups to put similar topics together

### PR DESCRIPTION
**Pull request by cellio**
We have enough communities now that the list is not super-easy to scan any more.  The goal here is twofold: put "related" communities together, and lead with more active ones to make a better first impression.  Please comment if you think I got the groupings/order wrong!

To make reviewing easier, 'cause git diff isn't going to be super-readable, here's a screenshot showing the new order:

browser screenshot

### CODE REVIEW

**Comment by trichoplax** [comment]
This reordering made me wonder if it would be beneficial to automate this, so we don't need to keep manually changing the order as activity varies between communities, so I raised the possibility of sorting buttons (which could default to activity) on Meta: https://meta.codidact.com/posts/288188

This would lose your grouping of communities though, so it depends how important that is. If grouping was less subjective I'd suggest having "grouped" as a sort option, but I'm not sure how much agreement there would be between different people on which communities should be adjacent.

**Comment by cellio** [comment]
@trichoplax this change is for the page at codidact.com, which is a static page (not served by qpixel).  While editing I also wondered about changing the order in the dropdown, dashboard, and footer, which would need to be done separately.  Your suggestion to give people sorting options is interesting; let's see what input we get from your meta post about how people would want it to work.

**Comment by cellio** [comment]
Per review feedback, moved Music to the end based on activity.

screenshot

**Review by superplane39 — CHANGES_REQUESTED** [review]
We should migrate the "site" wording to "community" in most cases; the category name for proposing new communities is also outdated.

**Review by superplane39 — APPROVED** [review]

**Pull request merged**
